# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Data-Toolkit
version:      0.2
version_from: 
installdirs:  site
requires:
    Carp:                          0
    Clone:                         0
    Data::Dumper:                  0
    Data::MultiValuedHash:         0
    Net::LDAP::Entry:              0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
