--- #YAML:1.0
name:               Data-Toolkit
version:            0.8
abstract:           Toolkit for manipulating attribute-value data. Useful in directory synchronisation systems and other data‐pump applications.
author:
    - Andrew Findlay <andrew.findlay@skills-1st.co.uk>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    Clone:                0
    Data::Dumper:         0
    Data::MultiValuedHash:  0
    DBD::CSV:             0
    Net::LDAP::Entry:     0
    SQL::Statement:       1.15
    Text::CSV_XS:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
